import LegalLayout, {
  Callout,
  H2,
  H3,
  LI,
  P,
  Table,
  UL,
  type LegalSection,
} from "@/components/legal/LegalLayout";

/**
 * Privacy Policy — drafted against the Personal Data Protection Act 2010,
 * as amended by the Personal Data Protection (Amendment) Act 2024.
 *
 * The factual descriptions here were written from a code-level audit of the
 * landing page and the RSVP platform. If what either app collects changes,
 * this page must change with it — an inaccurate policy is worse than none.
 *
 * Retention periods and the marketing/analytics statements are the defaults
 * recommended in the compliance pack; confirm before relying on them.
 */

const UPDATED = "21 July 2026";

const SECTIONS: LegalSection[] = [
  { id: "about", title: "About this policy" },
  { id: "collect", title: "Personal data we collect" },
  { id: "source", title: "Where we obtain your data" },
  { id: "sensitive", title: "Sensitive personal data" },
  { id: "purpose", title: "Why we process your data" },
  { id: "disclose", title: "Who we disclose it to" },
  { id: "retention", title: "How long we keep it" },
  { id: "transfer", title: "Transfers outside Malaysia" },
  { id: "rights", title: "Your rights" },
  { id: "security", title: "Security" },
  { id: "contact", title: "Contact and complaints" },
  { id: "changes", title: "Changes to this policy" },
  { id: "notis-bm", title: "Notis (Bahasa Malaysia)" },
];

export default function Privacy() {
  return (
    <LegalLayout
      title="Privacy Policy"
      metaTitle="Privacy Policy — AuraPixel"
      description="How Aura Pixel Creative Studio Sdn. Bhd. collects, uses, discloses and protects your personal data under the Malaysian Personal Data Protection Act 2010."
      path="/privacy"
      updated={UPDATED}
      intro="How we collect, use, disclose and protect your personal data — and the rights you have over it under the Malaysian Personal Data Protection Act 2010."
      sections={SECTIONS}
    >
      <H2 id="about">1. About this policy</H2>
      <P>
        <strong className="text-white">
          Aura Pixel Creative Studio Sdn. Bhd.
        </strong>{" "}
        (Registration No. 202601009966 (1672064-D)) (&ldquo;AuraPixel&rdquo;,
        &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is committed to
        protecting your personal data in accordance with the Personal Data
        Protection Act 2010 (the &ldquo;PDPA&rdquo;). For the purposes of the
        PDPA we are the <strong className="text-white">data controller</strong>{" "}
        of the personal data described below.
      </P>
      <P>This policy applies to:</P>
      <UL>
        <LI>
          our website at <strong className="text-white">aurapixel.live</strong>,
          including the enquiry form;
        </LI>
        <LI>
          our event registration platform at{" "}
          <strong className="text-white">aurapixel.live/rsvp</strong>; and
        </LI>
        <LI>our email and WhatsApp communications with you.</LI>
      </UL>
      <P>
        Where we run an event registration on behalf of a client, that client is
        a joint or independent controller of the attendee data for their own
        purposes. We will tell you who the event organiser is at the point of
        registration.
      </P>

      <H2 id="collect">2. Personal data we collect</H2>

      <H3>2.1 If you submit an enquiry on our website</H3>
      <P>
        Your name, company name, work email address, phone or WhatsApp number,
        the service you are interested in, and your indicated monthly budget
        range. All of these fields are mandatory — if you do not provide them we
        cannot respond to your enquiry.
      </P>

      <H3>2.2 If you register for an event</H3>
      <P>
        <em className="text-white/80">Mandatory:</em> your full name, email
        address, phone or WhatsApp number, and whether you will be attending.
      </P>
      <P>
        <em className="text-white/80">Optional:</em> your company or
        organisation, job title, industry, your role in relation to the event,
        whether you are bringing a guest and that guest&rsquo;s name, your meal
        preference or dietary requirements, and any message you choose to send
        us.
      </P>
      <P>
        <em className="text-white/80">Generated by us:</em> a registration
        reference, your seat or table allocation, a signed QR pass token,
        check-in timestamps, and records of the communications we have sent you.
      </P>

      <H3>2.3 If you are a guest brought by another attendee</H3>
      <P>
        We may hold your name because the attendee who invited you provided it.
        We ask attendees to obtain your agreement before doing so. You may ask
        us to remove your name at any time using the contact details in section
        11.
      </P>

      <H3>2.4 Technical data</H3>
      <P>
        Our hosting provider records standard server log data, including IP
        address, browser type and the time of your request, for security and
        reliability purposes.
      </P>
      <P>
        At the date of this policy our website does{" "}
        <strong className="text-white">not</strong> use analytics, advertising
        or tracking cookies. If we introduce them we will update this policy and
        provide a cookie notice before doing so.
      </P>

      <H2 id="source">3. Where we obtain your data</H2>
      <P>
        Directly from you through our forms; from the organiser or host of an
        event you have been invited to; from an attendee who has registered you
        as their guest; or from a registration form on a client&rsquo;s own
        website that feeds into our platform.
      </P>

      <H2 id="sensitive">4. Sensitive personal data</H2>
      <P>
        If you tell us about dietary requirements, that information may reveal
        your religious beliefs or your state of health. Under the PDPA this is{" "}
        <strong className="text-white">sensitive personal data</strong> and we
        process it only with your{" "}
        <strong className="text-white">explicit consent</strong>, which we
        request separately at the point of registration.
      </P>
      <P>
        We use it for one purpose only: to inform the event caterer of meal
        requirements. We share it with the caterer and the event organiser only
        so far as necessary, and we delete it in accordance with section 7.
      </P>
      <Callout title="Please note">
        Do not include medical details, diagnoses or medication information in
        any free-text field. We do not need it and we ask you not to provide it.
      </Callout>

      <H2 id="purpose">5. Why we process your data</H2>
      <P>
        We process your personal data for the following purposes, on the
        following bases under the PDPA:
      </P>
      <Table
        head={["Purpose", "Basis"]}
        rows={[
          [
            "Responding to your enquiry and preparing a proposal",
            "Your consent; steps taken at your request before a contract",
          ],
          [
            "Providing our services under a signed engagement",
            "Performance of a contract",
          ],
          [
            "Processing your event registration, issuing your pass, allocating seating and managing check-in",
            "Your consent; performance of a contract with the event organiser",
          ],
          [
            "Sending you event communications — confirmations, passes, reminders and changes",
            "Your consent",
          ],
          [
            "Providing attendance and event reports to the event organiser",
            "Our legitimate interest in delivering our contracted service",
          ],
          [
            "Marketing our services to you by email or WhatsApp",
            "Your consent — withdrawable at any time",
          ],
          [
            "Security, fraud prevention and maintaining our systems",
            "Our legitimate interest; compliance with the Security Principle",
          ],
          [
            "Complying with legal, tax and regulatory obligations",
            "Legal obligation",
          ],
        ]}
      />

      <H2 id="disclose">6. Who we disclose your data to</H2>
      <P>
        <strong className="text-white">We do not sell your personal data.</strong>{" "}
        We disclose it to:
      </P>
      <UL>
        <LI>
          <strong className="text-white">
            The event organiser or our client
          </strong>
          , where you registered for an event we administer on their behalf —
          including your name, contact details, attendance status and, where
          applicable, meal requirements.
        </LI>
        <LI>
          <strong className="text-white">Event suppliers</strong> such as
          caterers and venue security, limited to what they need.
        </LI>
        <LI>
          <strong className="text-white">Our service providers</strong> (see
          section 8), who process data on our instructions only.
        </LI>
        <LI>
          <strong className="text-white">Professional advisers</strong> —
          lawyers, accountants and insurers — where necessary.
        </LI>
        <LI>
          <strong className="text-white">
            Regulators, law enforcement or courts
          </strong>
          , where required by law.
        </LI>
        <LI>
          <strong className="text-white">A buyer or successor</strong>, in the
          event of a sale, merger or restructuring of our business.
        </LI>
      </UL>

      <H2 id="retention">7. How long we keep your data</H2>
      <Table
        head={["Category", "Retention period"]}
        rows={[
          [
            "Website enquiries that do not become clients",
            "24 months from last contact",
          ],
          [
            "Client records and engagement documents",
            "7 years after the end of the engagement, to meet tax and limitation requirements",
          ],
          [
            "Event registration and attendance records",
            "12 months after the event date",
          ],
          [
            "Dietary and meal-requirement data",
            "Deleted within 30 days after the event",
          ],
          [
            "Marketing consent records",
            "Until you withdraw consent, plus 24 months to evidence the withdrawal",
          ],
          [
            "Server and security logs",
            "As retained by our hosting provider, typically 30 days",
          ],
        ]}
      />
      <P>
        At the end of these periods we delete the data or permanently anonymise
        it so that you can no longer be identified from it.
      </P>

      <H2 id="transfer">8. Transfers outside Malaysia</H2>
      <P>
        We use reputable service providers located outside Malaysia. Your
        personal data will therefore be transferred to and processed in other
        countries. Our principal processors are:
      </P>
      <Table
        head={["Service", "Purpose", "Location"]}
        rows={[
          [
            "Cloud hosting & database providers",
            "Hosting our website and event platform, and storing registration data",
            "United States / global",
          ],
          [
            "Email delivery provider",
            "Sending confirmations, passes and event notifications",
            "United States",
          ],
          [
            "Messaging provider (WhatsApp)",
            "Sending WhatsApp confirmations and passes",
            "Singapore / United States",
          ],
        ]}
      />
      <P>
        Before transferring, we satisfy ourselves that the data will receive a
        level of protection substantially similar to that required by the PDPA,
        and we put contractual data protection terms in place with each
        provider.{" "}
        <strong className="text-white">
          By submitting your data to us you consent to these transfers.
        </strong>{" "}
        If you would prefer your data not to be transferred abroad, please
        contact us — but note that we may then be unable to provide the service.
      </P>

      <H2 id="rights">9. Your rights</H2>
      <P>Under the PDPA you have the right to:</P>
      <UL>
        <LI>
          <strong className="text-white">Access</strong> the personal data we
          hold about you. We will respond within{" "}
          <strong className="text-white">21 days</strong>. A prescribed fee may
          apply.
        </LI>
        <LI>
          <strong className="text-white">Correct</strong> data that is
          inaccurate, incomplete, misleading or out of date.
        </LI>
        <LI>
          <strong className="text-white">Withdraw your consent</strong> at any
          time. This does not affect processing already carried out.
        </LI>
        <LI>
          <strong className="text-white">Limit or object to processing</strong>{" "}
          that is causing, or is likely to cause, you damage or distress.
        </LI>
        <LI>
          <strong className="text-white">Stop direct marketing</strong> — an
          absolute right. You do not have to give a reason, and every marketing
          email includes an unsubscribe link.
        </LI>
        <LI>
          <strong className="text-white">Data portability</strong> — request
          that we transfer your data to another data controller in a structured,
          commonly used format, where technically feasible.
        </LI>
      </UL>
      <P>
        To exercise any of these rights, contact us using section 11. We may ask
        you to verify your identity first.
      </P>

      <H2 id="security">10. Security</H2>
      <P>
        We take practical steps to protect your personal data, including
        encryption in transit, access controls and authentication on
        administrative systems, time-limited session expiry, cryptographically
        signed event passes, and restricting access to those who need it.
      </P>
      <P>
        No system is completely secure. If a breach occurs that is likely to
        cause you significant harm, we will notify the Personal Data Protection
        Commissioner and you, as required by law.
      </P>

      <H2 id="contact">11. Contact and complaints</H2>
      <P>
        Questions, requests or complaints about this policy or your personal
        data:
      </P>
      <P>
        <strong className="text-white">
          Aura Pixel Creative Studio Sdn. Bhd.
        </strong>
        <br />
        Attn: Arveenthakumar, Founder &amp; Creative Director
        <br />
        11-07, The Boulevard Office, Lingkaran Syed Putra,
        <br />
        Mid Valley City, 59200 Kuala Lumpur, Malaysia
        <br />
        Email:{" "}
        <a
          href="mailto:privacy@aurapixel.live"
          className="text-primary transition hover:text-primary/80"
        >
          privacy@aurapixel.live
        </a>
        <br />
        Tel:{" "}
        <a
          href="tel:+60102841290"
          className="text-primary transition hover:text-primary/80"
        >
          +6010-284 1290
        </a>
      </P>
      <P>
        If you are not satisfied with our response, you may complain to the{" "}
        <strong className="text-white">
          Personal Data Protection Commissioner (Jabatan Perlindungan Data
          Peribadi)
        </strong>
        , Ministry of Digital, Malaysia —{" "}
        <a
          href="https://www.pdp.gov.my"
          target="_blank"
          rel="noreferrer"
          className="text-primary transition hover:text-primary/80"
        >
          pdp.gov.my
        </a>
        .
      </P>

      <H2 id="changes">12. Changes to this policy</H2>
      <P>
        We may update this policy from time to time. The current version is
        always at aurapixel.live/privacy with the &ldquo;last updated&rdquo;
        date shown above. Where changes are significant we will notify you
        directly.
      </P>

      <H2 id="notis-bm">13. Notis Perlindungan Data Peribadi</H2>
      <P>
        <em className="text-white/80">
          Section 7(3) of the PDPA requires this notice to be issued in both
          Bahasa Malaysia and English. The Bahasa Malaysia version follows.
        </em>
      </P>
      <Callout title="Bahasa Malaysia">
        <p className="font-semibold text-white">
          NOTIS PERLINDUNGAN DATA PERIBADI
        </p>
        <p className="mt-3">
          Aura Pixel Creative Studio Sdn. Bhd. (&ldquo;AuraPixel&rdquo;)
          memproses data peribadi anda menurut Akta Perlindungan Data Peribadi
          2010.
        </p>
        <ol className="mt-4 list-decimal space-y-2 pl-5">
          <li>
            <strong className="text-white">Data yang dikumpul:</strong> nama,
            alamat e-mel, nombor telefon/WhatsApp, nama syarikat, jawatan,
            industri, nama tetamu (&ldquo;+1&rdquo;), pilihan makanan, dan
            sebarang maklumat yang anda isi dalam ruangan mesej.
          </li>
          <li>
            <strong className="text-white">Sumber data:</strong> secara langsung
            daripada anda melalui borang kami, atau daripada penganjur acara
            yang menjemput anda.
          </li>
          <li>
            <strong className="text-white">Tujuan:</strong> memproses
            pendaftaran anda, mengeluarkan pas QR dan nombor tempat duduk,
            berhubung dengan anda mengenai acara tersebut, menguruskan
            pendaftaran masuk, dan menyediakan laporan kehadiran kepada
            penganjur acara.
          </li>
          <li>
            <strong className="text-white">Penzahiran:</strong> kepada penganjur
            acara dan pembekal acara seperti pihak katering, serta kepada
            penyedia perkhidmatan pihak ketiga kami — perkhidmatan hosting awan,
            penghantaran e-mel dan pemesejan.
          </li>
          <li>
            <strong className="text-white">
              Pemindahan ke luar Malaysia:
            </strong>{" "}
            penyedia perkhidmatan di atas terletak di luar Malaysia. Dengan
            menghantar borang kami, anda bersetuju data anda dipindahkan dan
            diproses di luar negara.
          </li>
          <li>
            <strong className="text-white">Data yang diwajibkan:</strong>{" "}
            ruangan bertanda (*) adalah wajib. Sekiranya anda tidak
            memberikannya, kami tidak dapat memproses pendaftaran anda.
          </li>
          <li>
            <strong className="text-white">Data peribadi sensitif:</strong>{" "}
            maklumat pilihan makanan mungkin mendedahkan kepercayaan agama atau
            kesihatan anda. Anda memberikan persetujuan nyata untuk kami
            memprosesnya bagi tujuan katering sahaja. Sila jangan kemukakan
            maklumat perubatan.
          </li>
          <li>
            <strong className="text-white">Hak anda:</strong> anda berhak
            mengakses dan membetulkan data anda, menarik balik persetujuan,
            mengehadkan pemprosesan, dan memohon mudah alih data. Hubungi{" "}
            <a
              href="mailto:privacy@aurapixel.live"
              className="text-primary transition hover:text-primary/80"
            >
              privacy@aurapixel.live
            </a>
            .
          </li>
          <li>
            Notis ini dikeluarkan dalam Bahasa Malaysia dan Bahasa Inggeris.
            Sekiranya terdapat percanggahan, versi Bahasa Inggeris akan
            digunapakai.
          </li>
        </ol>
      </Callout>
    </LegalLayout>
  );
}
